# Generated by Django 4.2 on 2023-04-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateField()),
                ('etat_signalement', models.CharField()),
                ('lieu', models.CharField()),
                ('type_signalement', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=20)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='gestion_ville.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('citoyen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_ville.citoyen')),
                ('poste', models.CharField(max_length=255)),
                ('date_naisse', models.DateField()),
                ('salaire', models.PositiveIntegerField()),
            ],
            bases=('gestion_ville.citoyen',),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_de_la_demande', models.DateField()),
                ('etat_de_la_demande', models.CharField(max_length=255)),
                ('cout', models.PositiveIntegerField()),
                ('delai_traitement', models.CharField(max_length=255)),
                ('numer_confirmation', models.CharField(max_length=255)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='gestion_ville.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('etat_davancement', models.PositiveIntegerField()),
                ('signalements', models.ManyToManyField(related_name='travaux', to='gestion_ville.signalement')),
                ('employes', models.ManyToManyField(related_name='travaux', to='gestion_ville.employe')),
            ],
        ),
    ]
