# Generated by Django 4.2.1 on 2023-06-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0005_alter_signalement_type_signalement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travail',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='date_fin_prevue',
        ),
    ]
