# Generated by Django 4.2.1 on 2023-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0006_remove_travail_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='etat_davancement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
