# Generated by Django 4.2.2 on 2023-06-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='citoyen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='gestion_ville.citoyen'),
        ),
    ]
