# Generated by Django 4.2.2 on 2023-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0002_alter_demande_citoyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='prenom',
            field=models.CharField(default='glauque', max_length=255),
            preserve_default=False,
        ),
    ]
