# Generated by Django 4.2.2 on 2023-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0003_citoyen_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='recup',
            field=models.BooleanField(default=False),
        ),
    ]
