# Generated by Django 4.2.2 on 2023-06-12 14:54

from django.db import migrations, models
import gestion_ville.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0004_demande_recup'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='filerecup',
            field=models.FileField(blank=True, null=True, upload_to='recup/', validators=[gestion_ville.models.validate_file_extension]),
        ),
    ]
