# Generated by Django 4.2.2 on 2023-06-12 16:19

from django.db import migrations, models
import gestion_ville.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0005_demande_filerecup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='filerecup',
            field=models.FileField(blank=True, default='avant cetait null', upload_to='recup/', validators=[gestion_ville.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
