# Generated by Django 4.2.2 on 2023-06-12 18:32

from django.db import migrations, models
import gestion_ville.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0007_alter_demande_fichier_alter_demande_filerecup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='fichier',
            field=models.FileField(upload_to='demande_files/', validators=[gestion_ville.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='demande',
            name='filerecup',
            field=models.FileField(blank=True, upload_to='recup/', validators=[gestion_ville.models.validate_file_extension]),
        ),
    ]
