# Generated by Django 4.2.2 on 2023-06-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ville', '0008_alter_demande_fichier_alter_demande_filerecup'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='fichier_telecharge',
            field=models.BooleanField(default=False),
        ),
    ]
